name: async_builder
description: Flutter Future and Stream builder with less boilerplate and better error handling.
version: 1.3.0
homepage: https://github.com/PixelToast/async_builder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ">=0.20.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: